name: simply_english
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  riverpod: ^2.4.9
  fl_chart: ^0.66.0
  hive: ^2.2.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  dio: ^5.4.0
  build_runner: ^2.4.8
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/fonts/

  fonts:
    - family: Outfit-Regular
      fonts:
        - asset: fonts/static/Outfit-Regular.ttf
          weight: 400
       
   

   
 
